/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.andres.vista;

import com.andres.controlador.MetodosDB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Andre
 */
public class Login extends javax.swing.JFrame {
    PreparedStatement preparedST = null;
    ResultSet result = null;
    
    private static boolean esOracle = true;
    private static boolean esSQLServer = false;
    
    private static String usuario = "";
    private static String contrasena = "";
    private static String instancia = "";
    private static String ipServidor = "";
    private static String puerto = "";

    public static boolean isEsOracle() {
        return esOracle;
    }

    public void setEsOracle(boolean esOracle) {
        Login.esOracle = esOracle;
    }

    public static boolean isEsSQLServer() {
        return esSQLServer;
    }

    public void setEsSQLServer(boolean esSQLServer) {
        Login.esSQLServer = esSQLServer;
    }

    public static String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        usuarioTextField.setText(usuario);
    }

    public static String getContrasena() {
        return contrasena;
    }

    public static void setContrasena(String contrasena) {
        Login.contrasena = contrasena;
    }

    public static String getInstancia() {
        return instancia;
    }

    public static void setInstancia(String instancia) {
        Login.instancia = instancia;
    }

    public static String getIpServidor() {
        return ipServidor;
    }

    public static void setIpServidor(String ipServidor) {
        Login.ipServidor = ipServidor;
    }

    public static String getPuerto() {
        return puerto;
    }

    public static void setPuerto(String puerto) {
        Login.puerto = puerto;
    }
    
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        motoBaseLabel = new javax.swing.JLabel();
        motorBDComboBox = new javax.swing.JComboBox<>();
        usuarioLabel = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        contrasenaLabel = new javax.swing.JLabel();
        motorTabbedPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        instanciaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ipServidorTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        puertoTextField = new javax.swing.JTextField();
        oracleConectarButton = new javax.swing.JButton();
        cancelarOracleButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sqlserverConectarButton = new javax.swing.JButton();
        ipServidorSQLServerTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        puertoSQLServerTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        baseDatosTextField = new javax.swing.JTextField();
        cancelarSQLServerButton = new javax.swing.JButton();
        contrasenaTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        motoBaseLabel.setText("Motor de base de datos");

        motorBDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "SQL Server" }));
        motorBDComboBox.setToolTipText("");
        motorBDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorBDComboBoxActionPerformed(evt);
            }
        });

        usuarioLabel.setText("Usuario");

        usuarioTextField.setText("andres");
        usuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextFieldActionPerformed(evt);
            }
        });

        contrasenaLabel.setText("Contraseña");

        jLabel1.setText("Instancia");

        instanciaTextField.setText("XE");
        instanciaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instanciaTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("IP servidor");

        ipServidorTextField.setText("localhost");

        jLabel3.setText("Puerto");

        puertoTextField.setText("1521");
        puertoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoTextFieldActionPerformed(evt);
            }
        });

        oracleConectarButton.setText("Conectar");
        oracleConectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oracleConectarButtonActionPerformed(evt);
            }
        });

        cancelarOracleButton.setText("Cancelar");
        cancelarOracleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarOracleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarOracleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oracleConectarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ipServidorTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(instanciaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puertoTextField))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(instanciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ipServidorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(puertoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oracleConectarButton)
                    .addComponent(cancelarOracleButton))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        motorTabbedPanel.addTab("Oracle", jPanel1);

        jLabel4.setText("IP servidor");

        sqlserverConectarButton.setText("Conectar");
        sqlserverConectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlserverConectarButtonActionPerformed(evt);
            }
        });

        ipServidorSQLServerTextField.setText("localhost");
        ipServidorSQLServerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipServidorSQLServerTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Puerto");

        puertoSQLServerTextField.setText("1433");
        puertoSQLServerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoSQLServerTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Base de datos");

        baseDatosTextField.setText("taller");
        baseDatosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseDatosTextFieldActionPerformed(evt);
            }
        });

        cancelarSQLServerButton.setText("Cancelar");
        cancelarSQLServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarSQLServerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseDatosTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puertoSQLServerTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ipServidorSQLServerTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cancelarSQLServerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqlserverConectarButton)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ipServidorSQLServerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(puertoSQLServerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqlserverConectarButton)
                    .addComponent(cancelarSQLServerButton))
                .addContainerGap())
        );

        motorTabbedPanel.addTab("SQL Server", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motoBaseLabel)
                    .addComponent(usuarioLabel)
                    .addComponent(contrasenaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(motorBDComboBox, 0, 216, Short.MAX_VALUE)
                    .addComponent(usuarioTextField)
                    .addComponent(contrasenaTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(motorTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motoBaseLabel)
                    .addComponent(motorBDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLabel)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenaLabel)
                    .addComponent(contrasenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motorTabbedPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void motorBDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorBDComboBoxActionPerformed
        // TODO add your handling code here:
        if(motorBDComboBox.getSelectedItem().equals("Oracle")){
            //setEsOracle(true);
            //setEsSQLServer(false);
            MetodosDB.setEsOracle(true);
            MetodosDB.setEsSQLServer(false);
            motorTabbedPanel.setSelectedIndex(0);
        }else if(motorBDComboBox.getSelectedItem().equals("SQL Server")){
            MetodosDB.setEsOracle(false);
            MetodosDB.setEsSQLServer(true);
            motorTabbedPanel.setSelectedIndex(1);
        }
    }//GEN-LAST:event_motorBDComboBoxActionPerformed

    private void usuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextFieldActionPerformed

    private void instanciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instanciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instanciaTextFieldActionPerformed

    private void oracleConectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oracleConectarButtonActionPerformed
        // TODO add your handling code here:
        MetodosDB.setEsOracle(true);
        MetodosDB.setEsSQLServer(false);
        MetodosDB.setUsuario(usuarioTextField.getText());
        MetodosDB.setContrasena(new String(contrasenaTextField.getPassword()));
        MetodosDB.setInstancia(instanciaTextField.getText());
        MetodosDB.setIpServidor(ipServidorTextField.getText());
        MetodosDB.setPuerto(puertoTextField.getText());
        if(MetodosDB.getConnection() != null){
            Principal principal = new Principal();
            
            this.setVisible(false);
            principal.setLocationRelativeTo(null);
            principal.setResizable(false);
            principal.setVisible(true);
        }
    }//GEN-LAST:event_oracleConectarButtonActionPerformed

    private void puertoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoTextFieldActionPerformed

    private void sqlserverConectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlserverConectarButtonActionPerformed
        // TODO add your handling code here:
        MetodosDB.setEsOracle(false);
        MetodosDB.setEsSQLServer(true);
        MetodosDB.setUsuario(usuarioTextField.getText());
        MetodosDB.setContrasena(new String(contrasenaTextField.getPassword()));
        MetodosDB.setIpServidor(ipServidorSQLServerTextField.getText());
        MetodosDB.setPuerto(puertoSQLServerTextField.getText());
        MetodosDB.setBaseDatos(baseDatosTextField.getText());
        if(MetodosDB.getConnection() != null){
            Principal principal = new Principal();
            
            this.setVisible(false);
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
        }
    }//GEN-LAST:event_sqlserverConectarButtonActionPerformed

    private void ipServidorSQLServerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipServidorSQLServerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipServidorSQLServerTextFieldActionPerformed

    private void puertoSQLServerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoSQLServerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoSQLServerTextFieldActionPerformed

    private void baseDatosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseDatosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseDatosTextFieldActionPerformed

    private void cancelarOracleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarOracleButtonActionPerformed
        // TODO add your handling code here:
        usuarioTextField.setText("");
        contrasenaTextField.setText("");
        instanciaTextField.setText("");
        ipServidorTextField.setText("");
        puertoTextField.setText("");
    }//GEN-LAST:event_cancelarOracleButtonActionPerformed

    private void cancelarSQLServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarSQLServerButtonActionPerformed
        // TODO add your handling code here:
        usuarioTextField.setText("");
        contrasenaTextField.setText("");
        ipServidorSQLServerTextField.setText("");
        puertoSQLServerTextField.setText("");
        baseDatosTextField.setText("");
    }//GEN-LAST:event_cancelarSQLServerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baseDatosTextField;
    private javax.swing.JButton cancelarOracleButton;
    private javax.swing.JButton cancelarSQLServerButton;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JPasswordField contrasenaTextField;
    private javax.swing.JTextField instanciaTextField;
    private javax.swing.JTextField ipServidorSQLServerTextField;
    private javax.swing.JTextField ipServidorTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel motoBaseLabel;
    private javax.swing.JComboBox<String> motorBDComboBox;
    private javax.swing.JTabbedPane motorTabbedPanel;
    private javax.swing.JButton oracleConectarButton;
    private javax.swing.JTextField puertoSQLServerTextField;
    private javax.swing.JTextField puertoTextField;
    private javax.swing.JButton sqlserverConectarButton;
    private javax.swing.JLabel usuarioLabel;
    private static javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
